config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/new_import'
  post 'dashboard/import'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :dashboard do
  #   collection do
  #      # import_new_file_path
  #     get 'dashboard/new', to: :new_import

  #     # import_file_path
  #     post :dashboard_import
  #   end
  # end
  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import.rb
class Import < ApplicationRecord

  def total_price
    unit_price*quantity
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index
    @imports = Import.all
  end

  def new_import
    @import = Import.new
  end

  def import
    ImportFileService.new.execute(params[:import][:import_file])

    flash[:success] = '<strong>File Imported!</strong>'

    redirect_to dashboard_index_path
  rescue StandardError => e
    flash[:error] = "There was a problem importing that file.<br>
        <strong>#{e.message}</strong><br>"

    redirect_to dashboard_new_import_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_form.html.erb
<%= form_for @import, url: dashboard_import_path, html: { multipart: true } do |f| %>
  <div class="field">
    <label class="label">Importar Arquivos</label>
    <div class="control">
      <%= f.file_field :import_file, class: 'input' %>
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= link_to 'Voltar', :back, class: "button is-danger"%>
    </div>
    <div class="control">
      <%= f.submit 'Enviar', class: "button is-link" %>
    </div>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

<div class="table-container">
  <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
    <tr>
      <th>#</th>
      <th>Comprador</th>
      <th>Descrição</th>
      <th>Preço Unitário</th>
      <th>Quantidade</th>
      <th>Endereço</th>
      <th>Fornecedor</th>
    </tr>
  </thead>
  <tbody>
    <% @imports.each_with_index do |import, index| %>
      <tr>
        <th><%= index %></th>
        <th><%= import.buyer %></th>
        <th><%= import.description %></th>
        <th><%= import.unit_price %></th>
        <th><%= import.quantity %></th>
        <th><%= import.address %></th>
        <th><%= import.supplier %></th>
      <tr>
    <% end %>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th>Total</th>
      <th><%= @imports.sum(&:total_price) %></th>

    </tr>
  </tbody>
  </table>
</div>

<%= link_to "Importa novos Dados", dashboard_new_import_path, class: "button is-primary" %>

app/views/dashboard/new_import.html.erb
<h1>Dashboard#import</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nama</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>